### ISSUE TITLE
download playlist not working

### ISSUE THREAD

**Issue by kitguy** [benkaiser/stretto#104] opened 2016-04-18 12:39 UTC
When you click on "Options" > "download playlist" it just download a file "download.zip" which contains no files at all, just folders.

**Comment by benkaiser** [comment] 2016-04-18 13:26
Okay, so the library we are using adm-zip was broken (see issue: https://github.com/cthackers/adm-zip/issues/127 ), and it appears adm-zip has not been updated in over a year, so I have switched out the zip library for [node-archiver](https://github.com/archiverjs/node-archiver).

If you re-pull from master and npm install again the issue should be fixed and playlist downloading should be super fast now. Are you installing from source @kitguy or are you using the pre-built packages on the releases page? If you are I might consider doing an updated release.

**Closed by benkaiser** 2016-04-18 13:26 UTC

**Comment by kitguy** [comment] 2016-04-18 14:00
Thanks for the fast reply! 

Hm, yes, I was using one of those pre-built packages. If you wouldnt mind doing an update release, it would be much appreciated!

**Comment by benkaiser** [comment] 2016-04-18 14:27
No worries,

I'll try and do it in the next week or so, but ping me if I forget
(currently studying full time I don't have loads of free time and I haven't
quite automated the build process as much as I would like so it takes a
while)

**Comment by ohnx** [comment] 2016-04-18 22:28
If there isn't much involvement needed (ie, you just start a process and keep it running), I can build the Mac, Windows x64, and Linux x64 binaries.

**Comment by benkaiser** [comment] 2016-04-18 22:41
It's got a few more steps (adding the ffmpeg binaries and then zipping the
folders with a high compression rate), but you can give it a shot if you
want. It is documented:
https://github.com/benkaiser/stretto/wiki/Building-and-Shipping-Electron-Binaries

I wonder if I can give access to just posting releases to other members...

**Comment by ohnx** [comment] 2016-04-18 23:22
I can mail them to you.

**Comment by benkaiser** [comment] 2016-04-19 01:49
@ohnx @kitguy rebuilt and released: https://github.com/benkaiser/stretto/releases/tag/v0.0.4

**Comment by kitguy** [comment] 2016-04-19 02:00
Sweet! Thank you @benkaiser @ohnx!

**Comment by kitguy** [comment] 2016-04-19 11:01
Guys, I couldn't download, here's the error I got:

![error](https://cloud.githubusercontent.com/assets/18451938/14636972/f57a4346-0604-11e6-8d42-5666f33be755.png)

**Comment by benkaiser** [comment] 2016-04-19 11:08
I'll see if I can reproduce.

**Comment by benkaiser** [comment] 2016-04-19 14:10
Good on me, not testing out your issue in electron (I only tested in the browser on the server version).

The downloading was only broken in electron, and I had to change the configuration I start the electron session with to fix it.
Because I had to build again today I decided to automate it, and so that has been done so future builds should be much faster / less hassle.

Anyway go checkout the 0.0.5 release which I've personally tested playlist downloading on (in Linux, fingers crossed it's fine in Windows): https://github.com/benkaiser/stretto/releases/tag/0.0.5

**Comment by kitguy** [comment] 2016-04-19 14:52
Oh, sorry. I tested on Electron, maybe that's the reason. 
Tested on browser and It's working fine! :smile:

**Comment by benkaiser** [comment] 2016-04-19 14:53
Well, it's still an issue if Electron is broken! So yeah just download the
updated version and itll work in Electron :)

**Comment by ohnx** [comment] 2016-04-19 15:12
The Mac version works for me!
